#! /usr/bin/bash
shopt -s extglob


#=========================== Create DB__2===========================
function createDb() {
    while true; do
         clear
        read -p "Please Enter Your Database Name: " DBNAME

        # Validation 1
        if [[ -z "$DBNAME" ]]; then
            echo -e "${RED} Error: Database name cannot be empty. Please try again. ${RESET} "
            continue
        fi

        # Validation 2
        if [[ ! "$DBNAME" =~ ^[a-zA-Z_][a-zA-Z0-9_]*$ ]]; then
            echo -e "${RED} Error: Database name can only contain letters, numbers, and underscores, must start with a letter ${RESET}"
            continue
        fi

        # Validation 3
        if [[ ${#DBNAME} -gt 15 ]]; then
            echo -e " ${RED}Error: Database name cannot exceed 64 characters. Please try again. ${RESET} "
            continue
        fi

        # Validation 4
        if [[ -e "$DBNAME" ]]; then
            echo -e "${RED} Error: Database '$DBNAME' already exists. Please choose a different name. ${RESET}"
            continue
        fi

        # validations pass
        mkdir "$DBNAME"
        echo "Database '$DBNAME' created successfully."
        break
    done
}

